### ISSUE TITLE
[question] No end-of-game info after a custom match

### ISSUE THREAD

**Issue by kryxeno** [RCVolus/league-prod-toolkit#112]
I just had a quick question.

So I checked the end-of-game module with just a random ranked match of a friend (5863038208), and it works perfectly fine.
However when I try it in a custom created tournament draft it doesn't seem to work (5861592351), while that is the intended usage (I assume).

I get that it's probably client related, but is there a way for it to work with customs?

**Comment by sdomi4** [comment]
Standard custom games are not available in the matchv5 API (although they have been available in the recent past since Riot apparently broke things).
Games created with a tournament code (e.g. through Battlefy or other platforms like it) are contained in the API, this is how we do it during our streams.
