### ISSUE TITLE
Graphs missing in End Game All in One

### ISSUE THREAD

**Issue by derianchow** [RCVolus/league-prod-toolkit#115]
When I load up the All in One screen, the left side KDA and stats portion shows up, but on the right side the Gold and Damage graphs are missing. If I use the individual Gold and End Game graphs they work perfectly fine. Any idea on how to fix this?

Also on Champ Select is it possible to change the color of the box behind names.

**Comment by sdomi4** [comment]
Apologies for the slow response – exam season is happening :(
The postgame stats are indeed broken on the current release. We have a partial fix in testing, but getting it released might take a while since we all have limited time at the moment.
You can try manually downgrading the module to a previous version to get some functionality back (although this might reintroduce some other bugs) by overwriting the end of game module with an older release from [here](https://github.com/rcv-prod-toolkit/module-league-end-of-game/releases).

Changing the color of the box is not trivial as the champ select module was not built with theming in mind. You can try changing it following the instructions [here](https://github.com/RCVolus/league-prod-toolkit/issues/114). The properties you'd want to change should be `background-color: black;` in the `.PlayerName` selector for the default background and `background-color: white;` in the `&.Active .PlayerName` selector for the currently highlighted pick.

**Comment by derianchow** [comment]
Ok thank you. Also I noticed in Custom Games the Runes don't work, is that also only usable through a Tournament Code lobby?

**Comment by Himyu** [comment]
This should be fixed with the newest version of the end of game module, please try to download the update and try again if the bug still exists.
