### ISSUE TITLE
[module-league-end-of-game] versitality improvement

### ISSUE THREAD

**Issue by figyl** [RCVolus/league-prod-toolkit#116]
Before I even begin, amazing work, I love the project so far and I can't express how excited I am.

### **Relevancy**
Currently the end of game module can only get its data via an API call which from my testing does not work with custom games in "tournament draft" setting, however, most of the data for these cases can be received via the LCU using the 
/lol-end-of-game/v1/eog-stats-block endpoint. 

Most of the data is there already unfortunately its not the full picture yet as it doesn't include towers, dragons, and datapoints for a gold graph.

### **Proposed solution**
Similar to [floh22](https://github.com/floh22)'s solution in [LeagueBroadcast](https://github.com/floh22/LeagueBroadcast) i would recommend using memory reading via the [league-observer-tool](https://github.com/RCVolus/league-observer-tool) to get the missing information.

This would enable everyone in every game-mode and even on tournament realm to get the data without an API call to Riot.

[edit]: In addition, it would also enable in-game gold graphs, experience and cs/min graphics to be served on demand. (Just like in the linked repo)

If you'd like me to elaborate further feel free to reach out!

**Comment by sdomi4** [comment]
Hello :) Thank you for your interest and the kind words.

The end of game module uses the matchv5 API to obtain postgame stats for a game – most custom games are not available there due to Riots policy. Custom games created with a tournament code *should* be available through matchv5, although it has been somewhat unreliable lately (see [this issue](https://github.com/RiotGames/developer-relations/issues/644)).

I have created a seperate feature request to add a fallback end of game stats page which only relies on the LCU data in #117.

We will not be implementing memory reading for a multitude of reasons (floh22 does an excellent job, our currently used technologies would not work well for memory reading, memory reading is a grey-ish area ToS-wise). There are also no plans to add OCR/computer vision solutions – the toolkit was built with only APIs as data sources in mind (if Riot at some point adds additional APIs/Endpoints we will be adding those to the toolkit).

**Comment by figyl** [comment]
Thanks for your quick response! Totally understandable.
