### ISSUE TITLE
Missing Config file?

### ISSUE THREAD

**Issue by ghost** [RCVolus/league-prod-toolkit#144]
During the install process, the install.bat file does not request for me to input values, unlike what's described in the wiki. The image below shows what happends after running the install, it looks like a config files is missing.
![Screenshot_7](https://user-images.githubusercontent.com/36971306/196057046-aa799c04-ed9e-4f8f-ac5d-d12047284120.png)

**Comment by sdomi4** [comment]
It looks like the module download failed. Could you try rerunning the installer?
If that doesn't work, you can download the config module [directly](https://github.com/rcv-prod-toolkit/plugin-config/releases/latest) and place it in the `modules` folder, rerun the installer, and then download individual modules from the toolkit.

**Comment by ghost** [comment]
By adding the config module it installs correctly, however at the 1st start it shows like this

![Screenshot_5](https://user-images.githubusercontent.com/36971306/196163654-bb51e8c7-6903-4bcf-8a7e-fa3c094dfec4.png)

If I restart the "start.bat" file it works but it won't load the visuals properly (and by what you have by default on the wiki) for example. Let me know if the stuff in the wiki it's just customized and that the following screenshots are displaying correctly

![Screenshot_7](https://user-images.githubusercontent.com/36971306/196168393-3206cd44-a5ff-4b4c-8b6e-c00223c789f7.png)
Icons the glow animations are missing

![Screenshot_8](https://user-images.githubusercontent.com/36971306/196169089-bb738b05-6225-479b-8c9a-8bfcfe5b9cc4.png)
Items and level-ups are entirely offset from the needed position, both start at the top edges (left the level 6, almost unreadable, and at the right the item buy). 

Note: I'm aware that there's a category for customization on the wiki but this just does not seem right to not match the feature overview by default

**Comment by sdomi4** [comment]
The manual download of modules skips downloading the default theme, which is why a bunch of assets are missing :(
You can get the default theme manually [here](https://github.com/rcv-prod-toolkit/theme-default/releases/latest), and then copy the directory into `\prod-toolkit\modules\plugin-theming\themes`.
Make sure the OBS browser source has no custom CSS configured; the default custom CSS breaks the positions.

In order to find out why the installer is failing, could you try opening the module list manually [here](https://sweet-pond-bc97.tatrix42.workers.dev/)? It should just return an array of modules and download links.

**Comment by Himyu** [comment]
That's caused by obs. If you remove the CSS that obs adds to the browser source it should be fine.
