### ISSUE TITLE
[ Question ] Using "lol-pick-ban-ui" layouts in "league-prod-toolkit"

### ISSUE THREAD

**Issue by kaianvn** [RCVolus/league-prod-toolkit#161]
**Hello!**

Basically, I started using [lol-pick-ban-ui](https://github.com/RCVolus/lol-pick-ban-ui) and it's [layout-volu-europe](https://github.com/RCVolus/lol-pick-ban-ui/tree/master/layouts/layout-volu-europe) layout to show the picks and bans during our [college tournament](https://www.twitch.tv/replaygamesifc), I find the layout simply amazing and now I found this [league-prod-toolkit](https://github.com/RCVolus/league-prod-toolkit) project, which it seems to me like an all-in-one broadcast package for League/Valorant.

Unforunately, [module-league-champselect-ui](https://github.com/rcv-prod-toolkit/module-league-champselect-ui) in it's original design, isn't quite the same as lol-pick-ban-ui, missing the team names and the pulsing colors, my question is: **Is there a way to integrate "layout-volu-europe" into "module-league-champselect-ui".** (for like, centralazing and using everything in one "app")

Thanks for the projects, they are helping us a lot!

**Comment by figyl** [comment]
It doesn't have the teamnames by design. You can customize the "Talk Team gfx" to give it an overall nice look. For example we used it like this: 
![image](https://user-images.githubusercontent.com/73833646/202160762-153b7941-6747-4fb0-8f4a-281656fe91d1.png)

Where the Team Talk gfx is just a background element to the pickban-ui:
![image](https://user-images.githubusercontent.com/73833646/202161014-31592e52-f62d-4b41-9a1d-21e4599ad39c.png)

Hope this helps!
