### ISSUE TITLE
[ Feature ] Please add an option to change the color of the "VS" between the team names. 

### ISSUE THREAD

**Issue by Jadiac5** [RCVolus/league-prod-toolkit#170]
I love the Teamnames feature etc. But the Yellow "VS" stands out way to much ):

Can we have a feature option like with the team name color select to change the "VS" color?

I'd like to know where the color is described in the files if you can't add an option so I can change it manually there.

Thank you for this weird request but it's just something that I would like to have on this.

**Comment by sdomi4** [comment]
You can already do this with themes – directly modifying module files is not recommended since you will lose your changes when updating modules.

There are a few ways to do this:

1. The yellow is the "accent color" of the default theme, it's also used in other pages (e.g., End of Game screens). You can change the accent color of the theme everywhere by creating a custom theme and modifying the `--accent-color` value.

2. You can individually customize the color of the "VS" by adding custom CSS to your theme:
To change the color in both the talk and the break overlay, add this to your theme (with whatever color code you desire):
```css
.vs {
  color: #123456;
}
```
If you want different colors for the overlays or only one to change, you can change them individually by adding:
```css
.module-teams-talk-gfx .vs {
  color: #123456;
}

.module-teams-pause-gfx .vs {
  color: #ABCDEF;
}
```

The steps to create custom themes are documented in the [wiki](https://github.com/RCVolus/league-prod-toolkit/wiki/3.-Customisation).
