### ISSUE TITLE
[ Bug ]

### ISSUE THREAD

**Issue by VorvXwiz** [RCVolus/league-prod-toolkit#208]
**Describe the bug**
Installation bug when running install.bat which leads to a syntax error in start.bat

**To Reproduce**
Believe the syntax error in start.bat is caused by the undefined within install.bat

**Expected behavior**
Working installation. Note start.bat in previous versions is also not working

**Screenshots**

**System:**
- OS: Microsoft
- Prod Tool Version: 1.3.6 

![installation](https://user-images.githubusercontent.com/67582944/211659621-58ffb6c8-7585-4a99-85a2-802e409b42c6.PNG)
![start bat file](https://user-images.githubusercontent.com/67582944/211659956-4348f651-6468-4a0a-ba10-cbcfa6278f05.PNG)

**Comment by Himyu** [comment]
The bug you are facing occurs when the community dragon is not up to date and can not serve you the current version of the item.bin.json, this should happen right after a new patch and can be fixed by setting a temporary alternative version for the static data like shown here https://github.com/RCVolus/league-prod-toolkit/wiki/FAQ#toolkit-shows-multiple-request-timed-out-errors--missing-assets
