### ISSUE TITLE
[Question] Creating custom overlays for in-game, pick-bans, etc...

### ISSUE THREAD

**Issue by Rookie001MC** [RCVolus/league-prod-toolkit#209]
I want to customize various aspects of the Toolkit, such as in-game overlays, pick-bans, etc... to somewhat match the look of LCK, LPL,.. for the upcoming tournament hosted by my University's Esports Club (and to touch up my rusty web development skills).
However, I'm having a hard time figuring out where to start. Therefore, I have a few questions:

- How to get the game data from the Toolkit?
- Can I use a JavaScript framework instead of plain HTML+CSS+JS for the overlays?
- Can I use the overlays from the [LoL Pick Ban UI](https://github.com/RCVolus/lol-pick-ban-ui) for the toolkit?

**Comment by sdomi4** [comment]
Depending on how much modification you have in mind, most things (if not everything) can be achieved through a custom theme. See the [wiki](https://github.com/RCVolus/league-prod-toolkit/wiki/3.-Customisation) for a small intro to theming.

You can change pretty much any CSS selector of any toolkit page directly within the theme – this allows you to modify everything short of the actual content.

If you do want to go down the route of building your own pages, the toolkit uses "LPTE" to send data between modules. I would suggest you look at the source of the existing modules (e.g., [module-league-ingame](https://github.com/rcv-prod-toolkit/module-league-in-game)) to familiarize yourself with LPTE.
You should be fine using whatever JS framework you prefer when building custom pages on top of the toolkit/LPTE.

The overlays from the Pick Ban UI are not directly portable to the toolkit – if you have a custom UI ready there, nothing stops you from using that instead of the toolkit version :)

**Comment by Rookie001MC** [comment]
Is the data from "LPTE" live, or do I have to keep track of some of it manually?

**Comment by sdomi4** [comment]
LPTE should contain all the live/up to date info you need. When in doubt you can always check the source for our modules and see how LPTE data is used :)

**Comment by Rookie001MC** [comment]
This also includes the game's timer too, right?

**Comment by Himyu** [comment]
Basically, you can use a framework instead of plain HTML and JS, see https://github.com/rcv-prod-toolkit/module-league-champselect-ui/tree/d28fa684c7f467351e3e54e0a59b5d7745e04879 where we use react instead of vanilla js, we also build some internal stuff with svelte and this is possible as well. if you want to include the LTPE in your favorite framework, just include the https://github.com/RCVolus/league-prod-toolkit/blob/main/frontend/frontend-lib.ts into it and you should be good to go. You either can just copy the code or import via '/static/main-bundle.js', I would use the second option for update purposes, if we change underlying structures you will also receive the changes as well. The last option is to import it through js import or require, just be aware that it is written in Typescript.
And yes LPTE will also provide you with live data and also ingame time.

**Comment by Rookie001MC** [comment]
I noticed in the `module-league-in-game` source code, there isn't anything related/referenced to team gold. Is the gold data available as well, or that is something I have to deal with myself?

**Comment by Himyu** [comment]
Atm, there is no way for us to get the gold out of the game since we don't use memory reading and we don't know another wat to get gold values.

**Comment by Rookie001MC** [comment]
Ah that's a bummer, I got the HUD almost done but this was kind of a major roadblock for me now 😅

**Comment by Himyu** [comment]
This is the reason why did not create a custom scoreboard yet.
