### ISSUE TITLE
Select and bans and end game [ Bug ]

### ISSUE THREAD

**Issue by overkido** [RCVolus/league-prod-toolkit#253]
the endgame is not counting the dragons or showing the icons in all in game and it is not showing the gold graphic of the game also know how to adjust iso?

https://user-images.githubusercontent.com/89580284/223129387-814ee7c1-26cc-4dff-9a70-44318b925447.mp4

the post dreft runes are also not showing in the dreft delay, I don't know, I put the player's name to recognize it, but I don't know why I don't show the runes, if you have a way to show comprints or a video on how to use the runes tool, I would be grateful.

![image](https://user-images.githubusercontent.com/89580284/223129732-25f51708-4ccf-49d3-a398-27fcafdeb14f.png)

**Comment by sdomi4** [comment]
It looks like the postgame stats come from the LCU fallback which doesn't include data on drakes and gold. Make sure the game is accessible through MatchV5 for everything to work fully (if it's a custom game, it has to be created with a tournament code).

Runes rely on the SpectatorV4-API; I've never gotten around to definitively testing it, but try setting lobby spectators to "everyone" instead of lobby only when creating your custom games.

There are no video guides yet. We will put out detailed guides once we finish some more features/changes.
