### ISSUE TITLE
End of Game All in One graph

### ISSUE THREAD

**Issue by syuanlyu** [RCVolus/league-prod-toolkit#274]
The End of Game All in One graph only shows the left part infoemation,but the right part is missing.
If I use the individual Gold graph is missing too.
 But the  End Game graph  work perfectly fine.

OS: Windows 10
Node: 16.14.0
Prod Tool Version: 1.4.1
Observer Tool Version: 5.0.0
Streaming Software & Version: OBS 28.1.2
Browser: Chrome
![image](https://user-images.githubusercontent.com/107873438/225543564-bdd5f419-c39b-410c-a626-c4153ca45a66.png)

**Comment by sdomi4** [comment]
This can occur when the postgame stats are loaded from the LCU fallback (the stats you see in the client after the game ends) instead of the intended matchv5 API. The LCU doesn't contain any info on Dragons/Elders/Barons, gold, and draft.

Before loading postgame stats make sure that:
- The game is visible in matchv5 (if it's a custom game, it has to be created with a tournament code)
- The game is set in the League State module

**Comment by syuanlyu** [comment]
Thanks.
