### ISSUE TITLE
[ Question ]

### ISSUE THREAD

**Issue by Miblizzard** [RCVolus/league-prod-toolkit#305]
Sorry to ask another question this early on.

The show gold, zoom in and out map, in caster cockpit don't seem to work/need development. Is there any way to fix this?

**Comment by sdomi4** [comment]
Map Zoom: This is intended to work with a [vMix integration](http://localhost:3003/pages/op-module-league-caster-cockpit/cockpit/index.html), otherwise nothing will happen.

Gold: This should work without issue; note that this just causes the observer tool to press "X" on the observer PC. If you're not tabbed into the game or have the button bound to something else, it won't work.

**Comment by KONGTINGYU** [comment]
I don't know how to configure and run, is there a schematic picture

**Comment by KONGTINGYU** [comment]
How do I get the API KEY?

**Comment by sdomi4** [comment]
> I don't know how to configure and run, is there a schematic picture

The [Wiki ](https://github.com/RCVolus/league-prod-toolkit/wiki/1.-Installation) has step by step installation instructions. If you run into problems, please open a [new issue](https://github.com/RCVolus/league-prod-toolkit/issues/new/choose).
