### ISSUE TITLE
[ Bug ] elo

### ISSUE THREAD

**Issue by Walace4458** [RCVolus/league-prod-toolkit#393]
My Start is bug on "elo" and i dont no fix this (sorry for my english i dont speak)
![AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA](https://github.com/RCVolus/league-prod-toolkit/assets/127856341/0a9520d2-2ee7-4970-9164-1dc7a9344492)

**Comment by sdomi4** [comment]
This usually happens when the observer opens a normal lobby instead of joining a custom game. Restarting the toolkit and only connecting the observer tool once inside a custom game lobby should avoid this issue.

We'll update docs / fix the crash in the future, but no firm timeline.

Sidenote: you seem to be running node 18.16; we are developing and testing on 16.7 so you might see unexpected behavior

**Comment by Himyu** [comment]
After som updates to the related modules, we should have fixed this crash. can you please try again and let us know if it is working for you now?

**Comment by HerXayah** [comment]
Ive encountered the same problem.
Latest Node LTS.
I think having it not work on norms/rankeds is not good.
I use the stuff for my Stream and the errors are a tad annoying, considering the PickBan Normal one works fine.
More Context:
Normal Game Lobby, you seemably fixed the error in the custom games for me though

**Comment by Himyu** [comment]
These tools were never made for using it in normal games / ranked games. Because this comes with a lot more limitations. We did not see any really big use cases for them that way. if there is a need for that though, we would have to consider these. But since Riot recently changed their policies for ranked games for champ select we would have to validate first, that our tools do not violate Riot's policies in any way.
We also strongly advise against using the ingame Farsight module of the observer tool ingame when you are playing yourself because this could trigger Riot's third-party dictation system and could get your account banned.

**Comment by HerXayah** [comment]
The usernames in Pick and Ban dont show on Pick and Ban, but your own.
I would vouch though, as it increases production value of my streams significantly and it just looks aweasom and is way easier for viewers to see.
👍

**Comment by Himyu** [comment]
We are currently not supporting using the prod tool while playing yourself, so we will not implement that feature for now but might in the future
