### ISSUE TITLE
[ Question ] custom module css with updates always gone

### ISSUE THREAD

**Issue by casbahcasts** [RCVolus/league-prod-toolkit#457]
**Is your question related to a problem? Please describe.**
I am always a bit frustrated when the custom css I changed in e.g: league-in-game: ingame; vanishes with an update.

**Describe alternatives you've considered**
I am not sure if the workaround is to just save a copy of the css before I update and once updated to just insert the changed parts manually again?

**Additional context**
So the reason for the custom css is that with the standard sizes e.g. the team score is out of place because its font is too large; baron power play is completely off. (see screenshot)

![image](https://github.com/RCVolus/league-prod-toolkit/assets/139663872/bb4fe5d6-e470-4f93-847d-fb15b837a055)

**Comment by Himyu** [comment]
Please have a look at our wiki and especially https://github.com/RCVolus/league-prod-toolkit/wiki/3.-Customisation for this kind of changes

**Comment by casbahcasts** [comment]
I am not quiet sure how this helps me. I use an own theme, which does not reset or anything. But the ingame css changes when updating the module e.g. module-league-in-game > frontend > gfx: "ingame" css does change with the updates. 

and I don't want to have a custom background in the team-tag scoreboard.

**Comment by sdomi4** [comment]
The module CSS files are not intended to be modified, which is why they are overwritten with every module update.

You can modify pretty much everything through themes which you modified directly in the overlay.
The custom background for the team-tag is just an example on how to use the CSS selectors for your modification inside a theme. Use any CSS selector and the theme will take precedence over the module CSS.

Make sure to save a copy of your theme before updating the theming module, that's something we haven't addressed yet.

**Comment by casbahcasts** [comment]
Okay thank you.

So I add for example the text from the ingame.scss to the theme-> index? 

I will try to figure out how and what I have to insert to the index.scss / theme. Sorry for so many questions.

**Comment by Himyu** [comment]
Basically the theme always override default design so you only need to put stuff in the theme you really mean to change instead of everything from the in game module CSS

**Comment by casbahcasts** [comment]
thanks :)
