### ISSUE TITLE
start.bat crashing when pick ban in-game opens

### ISSUE THREAD

**Issue by ViktorSterle** [RCVolus/league-prod-toolkit#64]
Greetings!

Since the new League of Legends patch 12.3. my Champselect UI is not responding!? I did everything step by step by the league-prod-toolkit/wiki Installation and it worked perfectly for me last month until this patch. I open start.bat, it initializes, then I open League Observer after opening League of Legends Client, and then it connects through the Observer tool normally. I open localhost:3003 and it shows me everything perfectly fine until I enter a game pick/ban lobby when my start.bat crashes and a JavaScript error pops up from League Observer. Please help!

[Screenshot 2022-02-07 194444](https://user-images.githubusercontent.com/91790507/152851749-f966d514-1452-4f1b-b983-4c2957d8cdf1.jpg)
!

**Comment by Himyu** [comment]
That is most likely due to the fact that the static content for league is not finished downloading.
Sometimes it takes Riot a bit of time to publish this data. If you run into trouble after one or to days after a new patch, just set your version in the config to the last patch and try it again later. And please make sure it finishes downloading before you use it :)
