### ISSUE TITLE
[ Question ] Some plugin issues (Runes, Plates, Drake, Powerplays)

### ISSUE THREAD

**Issue by Nauvyx** [RCVolus/league-prod-toolkit#648]
Hello,

First of all, thank you for the amazing work.

It's probably my fault, but after checking and enabling everything, I had some issues. During champselect, everything is going really well but the Runes plugin keeps displaying "NO_GAME", even with everything synced in the LoL Obeserver.

The second issue is concerning the plates, they're correctly showed in the scoreboard, but the counts are still at 0 in the plating tab (In-Game > Show Platings).

The third issue is concerning the dragon timer, it's working correctly but the second displayed dragon on the timer is always the same as the first (the bug is disappearing for the third dragon). There is also no pop-up when a team kills a dragon or a nash.

The last issue is concerning the Powerplays, they're showing correctly when I press the "Test" button but nothing happens during the game.

I've been working on it for some days but can't find an issue for these. 

Thanks for your help !

**Comment by FireFoXz09** [comment]
IF I am not mistaken, most of thoses things are related to the Live Event API, wich doesn't exist anymore and we have no way to get this data for now. (dragon kill, power plays). Else is maybe related to farsight nd memory reading, wich isn't updated as vanguard will most likely make it impossible to get this data legally (or without risking a ban).

Most of the "in-game" part of the toolkit is now obsolete and impossible to use for now because of Vanguard. All we can do is wait and hope...

**Comment by Nauvyx** [comment]
Thank you for your answer, I hope they're gonna implement Vanguard asap so we can keep working on it..
