### ISSUE TITLE
[ Question ] farsight in standby

### ISSUE THREAD

**Issue by Huncrysio** [RCVolus/league-prod-toolkit#649]
Hi, 
Sorry if this has already been discussed, i didnt find the answer scrolling throught the old issues
My farsight module keeps on standby, i got the draft to work but i cant make it work for the in game part
i also had a try with leagueBroadcast that i couldnt get to work at all
I've followed the installation guide

Thank you so much

**Comment by FireFoXz09** [comment]
Probably because the Farsight Module haven't been updated with the offsets of patch 14.7 , and/or isn't updated anymore by the team because of Vanguard incoming to League of Legends, wich will probably prevent Memory Reading, and access to in-game data.

So for now, forget Farsight AND Live Events, they aren't working anymore and probably won't work in the future (except if there is a miracle) :(
