### ISSUE TITLE
i need some help

### ISSUE THREAD

**Issue by NaVTSLOL** [RCVolus/league-prod-toolkit#663]
Good evening directly from Brazil, guys I need help to run a championship, I discovered this way, but the prod tool kit is no longer working for me after vanguard, can you upload a video with the tutorial teaching the features and how to modify them? some terms when translated are not the same and you may not understand what I want either, I just need a video tutorial on how it works, thank you very much for your attention.

**Comment by NaVTSLOL** [comment]
![image](https://github.com/RCVolus/league-prod-toolkit/assets/168887234/77fc1a7b-5b72-41bb-a503-46aa5709b97e)

and I can't use it from here, does anyone know how to make it work?

**Comment by NaVTSLOL** [comment]
Note: I'm not a programmer, but I have some friends who are helping me.

**Comment by sdomi4** [comment]
The ingame scoreboard feature no longer works due to Vanguard, there isn't a (easy) way around it, as noted in the readme:
"A lot of these [ingame] features are impacted by the removal of the LiveEvents API and the introduction of Vanguard. Level ups, item purchases, the killfeed and inhibitor timers should still work."

**Comment by NaVTSLOL** [comment]
Any updates on the personalized feed?

**Comment by daisukedd** [comment]
Salve @NaVTSLOL, acompanho o projeto também, sou do Brasil.
