### ISSUE TITLE
[ Question ] Prod Tool Working?

### ISSUE THREAD

**Issue by hokkino** [RCVolus/league-prod-toolkit#744]
What is working and not working for League Spec/Ingame in this repo?

Is everything working?

Because early next year I am starting a big event, and was looking for using it.

**Comment by sdomi4** [comment]
Assume most of the ingame features are broken and nothing has been updated since the start of season 14 (as in, no grubs and such). We are not working on this very actively at the moment, so expect limited support and updates.
Since you have time, I recommend taking a look at what our friends at bluebottle.gg are working on (not yet released, but should be in time for you)
