### ISSUE TITLE
I'm asking because I can't use it on the same network

### ISSUE THREAD

**Issue by sod101316** [RCVolus/league-prod-toolkit#87]
Is it possible to connect from the outside if I open port 3003 through port forwarding on the computer with the toolkit program running?

**Comment by sdomi4** [comment]
Yes, this should work, although we don't recommend this since there is no authentication yet. At the moment, we run the toolkit within a ZeroTier VPN for remote productions.
We are currently working on an authentication method so the toolkit can be hosted publically without concerns (for reference, see issue #55 and PR #85)
