### ISSUE TITLE
Running start.bat results in invaild json error

### ISSUE THREAD

**Issue by wsthilaire** [RCVolus/league-prod-toolkit#94]
**Describe the bug**
when you run start.bat an invalid json error appears, the error is caused by the program looking for patch 12.6 on the community dragon despite 12.6 not existing on the community dragon

FetchError: invalid json response body at https://raw.communitydragon.org/12.6/game/global/items/items.bin.json reason: Unexpected token < in JSON at position 0
    at C:\obs league resources\league-prod-toolkit-develop123\league-prod-toolkit-develop\modules\static-league\node_modules\node-fetch\lib\index.js:272:32
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async StaticData.getAdditionalFiles (C:\obs league resources\league-prod-toolkit-develop123\league-prod-toolkit-develop\modules\static-league\dist\StaticData.js:190:25) {
  type: 'invalid-json'

**To Reproduce**
1. run start.bat

**Expected behavior**
launch the start.bat

**Desktop (please complete the following information):**
 - OS: windows 11
 - Browser chrome
 - Version latest?

**Comment by sdomi4** [comment]
As you correctly identified, this is due to new patch data not being immediately available on patch days. The crash will be fixed in an upcoming release (see #79). As far as I can see, 12.6 data is now available on communitydragon, so you should be fine to go again :)

For a short-term workaround, you can also manually set the game version the module tries to download by adding `"gameVersion": "12.5"` (or whatever the patch before is) to the static-league object in config.json.
